### ISSUE TITLE
rebuild config into mysql storage

### ISSUE THREAD

**Issue by worldmc** [TrackingTeam/Inventory-Track#3]
rebuild config using a mysql based config setup.

**Comment by tankerkiller125** [comment]
Take a look at pc-track or issue-track for an idea on how to-do it

**Comment by tankerkiller125** [comment]
The settings.sql file along with the Config Class are now in TrackingTeam/MVC-Framework

**Comment by worldmc** [comment]
failed hardcore. will try later on. issue in TrackingTeam/MVC-Framework database connection methodes. 

@tankerkiller125:
```php
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Notice:  Use of undefined constant DB_TYPE - assumed 'DB_TYPE' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Notice:  Use of undefined constant DB_HOST - assumed 'DB_HOST' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Notice:  Use of undefined constant DB_NAME - assumed 'DB_NAME' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Notice:  Use of undefined constant DB_PORT - assumed 'DB_PORT' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Notice:  Use of undefined constant DB_CHARSET - assumed 'DB_CHARSET' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Notice:  Use of undefined constant DB_USER - assumed 'DB_USER' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Notice:  Use of undefined constant DB_PASS - assumed 'DB_PASS' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17
[Wed May 06 19:35:57.528210 2015] [:error] [pid 14688:tid 956] [client ::1:63037] PHP Fatal error:  Uncaught exception 'PDOException' with message 'could not find driver' in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php:17\nStack trace:\n#0 V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php(17): PDO->__construct('DB_TYPE:host=DB...', 'DB_USER', 'DB_PASS', Array)\n#1 V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\Config.php(15): DatabaseFactory->getConnection()\n#2 V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\Application.php(87): Config::get('DEFAULT_CONTROL...')\n#3 V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\Application.php(28): Application->createControllerAndActionNames()\n#4 V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\public\\index.php(17): Application->__construct()\n#5 {main}\n  thrown in V:\\bitami\\apache2\\htdocs\\kinderdorpV2\\application\\core\\DatabaseFactory.php on line 17

```

**Comment by worldmc** [comment]
Done, implemented on master
